/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg7_carlosromero;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Will
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.BLACK);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreCajero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombreProducto = new javax.swing.JTextField();
        TiempoProducto = new javax.swing.JSpinner();
        PrecioProducto = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CajeroCombobox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ProductosCombobox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        NombreCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        EdadCliente = new javax.swing.JSpinner();
        bCrearClientes = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(500, 500));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(500, 500));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 500));
        jTabbedPane1.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));
        jPanel1.add(NombreCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 140, 30));

        jButton1.setText("Agregar Cajero");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jTabbedPane1.addTab("Creacion de Cajero", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Precio");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tiempo de Procesamiento (Segundos):");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));
        jPanel2.add(NombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 210, 30));

        TiempoProducto.setModel(new javax.swing.SpinnerNumberModel());
        jPanel2.add(TiempoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 70, -1));

        PrecioProducto.setModel(new javax.swing.SpinnerNumberModel(0.99d, null, null, 0.5d));
        jPanel2.add(PrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 190, 70, -1));

        jButton2.setText("Agregar Producto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jTabbedPane1.addTab("Creacion de Productos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.add(CajeroCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 290, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cajero:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre Cliente:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jPanel3.add(ProductosCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 290, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Productos:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jButton3.setText("Agregar a Orden");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));
        jPanel3.add(NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 200, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Edad de Cliente:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        EdadCliente.setModel(new javax.swing.SpinnerNumberModel());
        jPanel3.add(EdadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 70, -1));

        bCrearClientes.setText("Crear Cliente");
        bCrearClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCrearClientesMouseClicked(evt);
            }
        });
        jPanel3.add(bCrearClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jButton5.setText("Realizar Compra");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 170, 40));

        jTabbedPane1.addTab("Ventas", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jButton6.setText("Guardar Archivo");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Cargar Archivo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addGap(203, 203, 203))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jButton6)
                .addGap(73, 73, 73)
                .addComponent(jButton7)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Archivos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String Nombre=NombreCajero.getText();
        int ID=(int) Math.floor(Math.random() * 12345 + 1);
        Cajeros Cajero=new Cajeros(Nombre, ID);
        ArrayList<Orden> Ordenes=new ArrayList();
        Cajero.setOrdenes(Ordenes);
        cajeros.add(Cajero);
        DefaultComboBoxModel model=(DefaultComboBoxModel) CajeroCombobox.getModel();
        model.addElement(Cajero.toString());
        CajeroCombobox.setModel(model);
        JOptionPane.showMessageDialog(this, "Cajero Creado", "Creado", 1);
        Ventana ventana=Cajero.getVentana();
        ventana.CajeroNombre.setText(Nombre);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String nombre=NombreProducto.getText();
        double precio=(double)PrecioProducto.getValue();
        int tiempo=(Integer)TiempoProducto.getValue();
        Productos pro=new Productos(nombre, precio, tiempo);
        productos.add(pro);
        DefaultComboBoxModel model=(DefaultComboBoxModel) ProductosCombobox.getModel();
        model.addElement(pro.toString());
        ProductosCombobox.setModel(model);    
        JOptionPane.showMessageDialog(this, "Producto Creado", "Creado", 1);
        Todo.add(pro);
    }//GEN-LAST:event_jButton2MouseClicked

    private void bCrearClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCrearClientesMouseClicked
        productoscliente=new ArrayList();
        Orden=new Orden();
        String nombre=NombreCliente.getText();
        int edad=(Integer)EdadCliente.getValue();
        Cliente cliente=new Cliente(nombre, edad, null);
        clientes.add(cliente);
        System.out.println(cliente.toString());
        JOptionPane.showMessageDialog(this, "Cliente Creado", "Creado", 1);
    }//GEN-LAST:event_bCrearClientesMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int x=ProductosCombobox.getSelectedIndex();
        Productos pro=productos.get(x);
        productoscliente.add(pro);
        System.out.println(productoscliente);
        JOptionPane.showMessageDialog(this, "Producto Agregado", "Creado", 1);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        int x=CajeroCombobox.getSelectedIndex();
        Cajeros cajero=cajeros.get(x);
        Orden=new Orden(cajero, clientes.get(clientes.size()-1), productoscliente);
        clientes.get(clientes.size()-1).setOrden(Orden);
        cajero.getOrdenes().add(Orden);
        cajero.Seguir();
        System.out.println(Orden.toString());
        cajero.EnviarOrden(Orden);
        Thread proceso=new Thread(cajero);
        proceso.start();
        JOptionPane.showMessageDialog(this, "Proceso Iniciado.", "Comprar", 1);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        Guardar("ArchivoDeSupermercado", "WILL", "Archivo de Supermercado");
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void Guardar(String Nombre, String Extension, String Tipo) {
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(Tipo, Extension);
        jfc.addChoosableFileFilter(filtro);
        jfc.setSelectedFile(new File(Nombre + "." + Extension));
        int seleccion = jfc.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            Administracion ad = new Administracion(jfc.getSelectedFile().getPath());
            ad.CargarArchivo();
            System.out.println("Guardar:");
            for (int i = 0; i < Todo.size(); i++) {
                ad.AgregarElemento(Todo.get(i));
                System.out.println(Todo.get(i));
            }
            try {
                ad.EscribirArchivo();
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Guardado", "Guardado", 1);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CajeroCombobox;
    private javax.swing.JSpinner EdadCliente;
    private javax.swing.JTextField NombreCajero;
    private javax.swing.JTextField NombreCliente;
    private javax.swing.JTextField NombreProducto;
    private javax.swing.JSpinner PrecioProducto;
    private javax.swing.JComboBox<String> ProductosCombobox;
    private javax.swing.JSpinner TiempoProducto;
    private javax.swing.JButton bCrearClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    ArrayList<Cliente> clientes=new ArrayList();
    ArrayList<Cajeros> cajeros=new ArrayList();
    ArrayList<Productos> productos=new ArrayList();
    Orden Orden=new Orden();
    ArrayList<Productos> productoscliente=new ArrayList();
    Ventana VentanaActual;
    ArrayList Todo=new ArrayList();
}
